version: '2'
services:
  db:
    image: mongo
    ports:
      - 27017
  alainxyz:
    image: alain.xyz:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    links:
      - db